# S3 Transfer Tool Configuration

# AWS Configuration
aws:
  # AWS region where the S3 bucket is located
  region: us-east-1
  # S3 bucket name
  bucket: ${AWS::AccountId}-s3transfer-${AWS::Region}

# Directory Configuration
directories:
  # Local directory for uploads
  upload: ./upload
  # Local directory for downloads
  download: ./download

# Basic Settings
sync:
  # Whether to delete files that don't exist in source
  delete_missing: false

# Logging Configuration
logging:
  # Log file path
  file: ./logs/sync.log
  # Log level (debug, info, warn, error)
  level: info
  # Maximum log file size in MB
  max_size: 10
  # Number of backup log files to keep
  backups: 3

# Performance Settings
performance:
  # Chunk size for multipart uploads in bytes
  chunk_size: 8388608  # 8MB
  # Maximum retry attempts for failed transfers
  max_retries: 3
  # Delay between retries in seconds
  retry_delay: 5
  # Bandwidth limit in bytes per second (0 for unlimited)
  bandwidth_limit: 0

# Security Settings
security:
  # Whether to verify file integrity after transfer
  verify_integrity: true
  # Whether to encrypt files before upload
  encrypt_files: false
  # Encryption algorithm (if encrypt_files is true)
  encryption_algorithm: AES-256 